import { Injectable } from '@angular/core';
import * as echarts from 'echarts';

// this svg pathData is generated by Adobe Illustrator (Ai)
const hollowRect = 'path://m315,493H0V0h315v493Zm-10-368H9v358h296V125Z';

namespace EchartsGraphic{
  export enum Colour {
    white = '#ffffff',
    black = '#000000',
    grey = '#D0D0D0',
    textGrey = '#8E8E8E',
    green = '#00A600',
    yellow = '#f7941d',
    red = '#ee3c39',
  };
  export enum Font{
    header = '16px sans-serif',
    utilisation = '22px sans-serif',
    status = '16px sans-serif',
  };
}

@Injectable({
  providedIn: 'root'
})
export class EchartsGraphicService {
  constructor() { }
  private getRectangle(
    x: number, 
    y: number, 
    width: number, 
    height: number, 
    colour: EchartsGraphic.Colour,
  ){
    return {
      type: 'rect',
      shape: {
        x: x,
        y: y,
        width: width,
        height: height,
      },
      style: {fill: colour},
    };
  }

  private getText(
    x: number,
    y: number,
    text: string,
    font: EchartsGraphic.Font,
    colour = EchartsGraphic.Colour.black,
  ) {
    return {
      type: 'text', 
      x:x, 
      y:y, 
      style:{
        text: text,
        fill: colour,
        font: font,
      }
    };
  }
  getVMGroup(): echarts.GraphicComponentOption {
    let VMGroup: echarts.GraphicComponentOption = {
      type: 'group',
      draggable: true,
      onclick: () => console.log('VM clicked'),
      children: [
        this.getRectangle(50, 50, 64, 100, EchartsGraphic.Colour.green),
        this.getRectangle(50+3, 50+27, 58, 70, EchartsGraphic.Colour.white),
        this.getText(50+15, 50+6,'VM1',EchartsGraphic.Font.header, EchartsGraphic.Colour.white),
        this.getText(50+11, 50+40, '20%', EchartsGraphic.Font.utilisation),
        this.getText(50+9, 50+70, 'Online', EchartsGraphic.Font.status),
      ]
    }
    return VMGroup;
  };
}
