import { Injectable } from '@angular/core';
import * as echarts from 'echarts';

// this svg pathData is generated by Adobe Illustrator (Ai)
const hollowRect = 'path://m315,493H0V0h315v493Zm-10-368H9v358h296V125Z';

enum GraphicColourCode {
  colourWhite = '#ffffff',
  colourBlack = '#000000',
  colourGrey = '#D0D0D0',
  colourTextGrey = '#8E8E8E',
  colourGreen = '#00A600',
  colourYellow = '#f7941d',
  colourRed = '#ee3c39',
}

@Injectable({
  providedIn: 'root'
})
export class EchartsGraphicService {
  constructor() { }
  private getRectangle(
    x: number, 
    y: number, 
    width: number, 
    height: number, 
    colour: GraphicColourCode,
  ){
    return {
      type: 'rect',
      shape: {
        x: x,
        y: y,
        width: width,
        height: height,
      },
      style: {fill: colour},
    }
  }
  getVMGroup(): echarts.GraphicComponentOption {
    let VMGroup: echarts.GraphicComponentOption = {
      type: 'group',
      draggable: true,
      onclick: () => console.log('VM clicked'),
      children: [
        this.getRectangle(50, 50, 64, 100, GraphicColourCode.colourGreen),
        this.getRectangle(50+3, 50+27, 58, 70, GraphicColourCode.colourWhite),
      ]
    }
    return VMGroup;
  };
}
